version: '3.8'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_DATABASE: jwt-test
      MYSQL_USER: jwt
      MYSQL_PASSWORD: jwt
    ports:
      - '3306:3306'